alias: Speicherentladung aktivieren
description: >-
  Aktiviert die Entladung der Speicher Batterie, wenn der Helfer auf Aus
  geschaltet wird.
trigger:
  - platform: state
    entity_id:
      - input_boolean.helper_home_battery_discharge_disabled
    from: "on"
    to: "off"
condition: []
action:
  - alias: Self Use Mode setzen
    service: select.select_option
    target:
      entity_id:
        - select.sofar_energy_storage_mode
    data:
      option: Self Use
mode: single