alias: Speicherentladung deaktiveren
description: >-
  Deaktiviert die Entladung der Speicher Batterie, wenn der Helfer auf An
  geschaltet wird.
trigger:
  - platform: state
    entity_id:
      - input_boolean.helper_home_battery_discharge_disabled
    from: "off"
    to: "on"
condition: []
action:
  - alias: Passive Mode setzen
    service: select.select_option
    target:
      entity_id:
        - select.sofar_energy_storage_mode
    data:
      option: Passive Mode
  - alias: Entladeleistung auf 0 setzen
    service: number.set_value
    target:
      entity_id:
        - number.sofar_passive_minimum_batter_power
    data:
      value: "0.0"
  - alias: Batterieleistung setzen
    service: button.press
    target:
      entity_id:
        - button.sofar_passive_update_battery_charge_discharge
    data: {}
mode: single